# Generated by Django 6.0.3 on 2026-03-16 17:59

import django.contrib.auth.models
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="CustomUser",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                (
                    "is_superuser",
                    models.BooleanField(
                        default=False,
                        help_text="Designates that this user has all permissions without explicitly assigning them.",
                        verbose_name="superuser status",
                    ),
                ),
                (
                    "first_name",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="first name"
                    ),
                ),
                (
                    "last_name",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="last name"
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True, max_length=254, verbose_name="email address"
                    ),
                ),
                (
                    "is_staff",
                    models.BooleanField(
                        default=False,
                        help_text="Designates whether the user can log into this admin site.",
                        verbose_name="staff status",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Designates whether this user should be treated as active. Unselect this instead of deleting accounts.",
                        verbose_name="active",
                    ),
                ),
                (
                    "date_joined",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="date joined"
                    ),
                ),
                (
                    "employee_id",
                    models.CharField(
                        help_text="Unique identifier used for login (e.g. EMP001)",
                        max_length=50,
                        unique=True,
                        verbose_name="Employee ID",
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[("employee", "Employee"), ("admin", "Admin")],
                        default="employee",
                        max_length=10,
                        verbose_name="Role",
                    ),
                ),
                (
                    "groups",
                    models.ManyToManyField(
                        blank=True,
                        help_text="The groups this user belongs to. A user will get all permissions granted to each of their groups.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.group",
                        verbose_name="groups",
                    ),
                ),
                (
                    "user_permissions",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Specific permissions for this user.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.permission",
                        verbose_name="user permissions",
                    ),
                ),
            ],
            options={
                "verbose_name": "User",
                "verbose_name_plural": "Users",
                "ordering": ["last_name", "first_name"],
            },
            managers=[
                ("objects", django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name="TimeRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "date",
                    models.DateField(
                        help_text="The calendar date this record belongs to (auto-set to today on creation)",
                        verbose_name="Work Date",
                    ),
                ),
                (
                    "clock_in",
                    models.DateTimeField(
                        blank=True,
                        help_text="Timestamp when the employee clocked in",
                        null=True,
                        verbose_name="Clock In",
                    ),
                ),
                (
                    "clock_out",
                    models.DateTimeField(
                        blank=True,
                        help_text="Timestamp when the employee clocked out",
                        null=True,
                        verbose_name="Clock Out",
                    ),
                ),
                (
                    "observation",
                    models.TextField(
                        blank=True,
                        help_text="Optional note added by the employee for this record",
                        null=True,
                        verbose_name="Observation",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="time_records",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Employee",
                    ),
                ),
            ],
            options={
                "verbose_name": "Time Record",
                "verbose_name_plural": "Time Records",
                "ordering": ["-date", "-clock_in"],
                "unique_together": {("user", "date")},
            },
        ),
    ]
